### ISSUE TITLE
Issue with temprorary page titles

### ISSUE THREAD

**Issue by grapherdity** [chris-kent/Confluence-Blog-Tools#10]
Hi,

thank you very much for this pretty useful add-on.

Sadly we have an issue since the last couple of day's. We are using the Page to Blog Macro embedded into a Page Template. Actually it was working quite well for a while, but lately causing some issues:

After the Page was saved and converted to a Blog Post, the page title still remain with "pagetoblog-26247270" for the Post. The original Confluence Page used temporarily is still existing. So we have this content twice. It seems that the conversion interrupted for some reason and the process got stuck somewhere in middle. 

We are using Confluence 5.8.14 and Version 3.1 of your add-on.

Any ideas?

Thank you very much,
Peter

**Comment by chris-kent** [comment]
Hi Peter,

Thanks for your feedback, unfortunately what you have described is a bug in
the work around I had to do since Atlassian broke the feature my plugin
uses.  I will need to look at this.

The good news for you is that you don't need version 3.1, it really only is
needed for Confluence 5.10.x and I thought I successfully only used the
workaround for those versions.

For your version the plugin should use the designed feature and work as it
did in plugin version 2.9.

For now, you can revert back to 2.9 and I'll fix the compatibility for 3.1
so you won't pick it up again.

As for the duplicates, simply delete the copy in the Pages section, and
rename the blog by removing the pagetoblog-xxxxx.

Cheers
Chris

**Comment by grapherdity** [comment]
Hi Chris,

thanks for the quick response. Ok, we will try reverting back to version 2.9.

Thank you for your support.

Cheers,
Peter

**Comment by chris-kent** [comment]
Hi Peter,

No worries.  I found the bug too, but it is easier for me to just mark my
version 3.1 compatible with Confluence 5.10.0 - 5.10.5 and this hides the
bug from other versions, which I have done.  So hopefully no one else will
trip over this.

This next release will fix the bug and I will make it compatible with your
version.  I think there is one new feature in this version that is not in
2.9 -> the ability to convert multiple pages to blogs in one transaction -
when using the Page Tool menu.

Thanks for your help.

Cheers
Chris

**Comment by grapherdity** [comment]
Hi Chris,

we've tested version 3.2 today and yeah it's working again. Thanks for fixing. :)

Is this version ready for Confluence 5.10+ or is there still trouble with it?

Thanks,
Peter

**Comment by chris-kent** [comment]
Hi Peter,

Thanks for the feedback, and yes this version is (should be) working for
5.10.x using a work-around which I developed in consultation with
Atlassian. The only problem with the work-around is that it is slower to
create the blog from the template as it uses code both in the server and
browser and these need to synchronise actions with each other, which was a
bit tricky (and I must say prone to errors if the server is unresponsive or
slow).

The good news is that Atlassian fixed this in Confluence 6.0+ so if you
wait till that is released, very soon, then I would suggest going straight
to 6.0.  I say this not just because of my plugin, but since they are
releasing a major version so quickly (ie. 5.10.0 is only months old) then
there might just be many other improvements in 6.0 :)

Cheers
Chris

**Comment by grapherdity** [comment]
Hi Chris,

thanks again. It's good to know the Atlassian cooperated with you on this. I'm pretty excited. :)

I think we will wait for Confluence 6.0. Since your add-on is working again, there actually no need for hurry. I hope the waiting pays off. :)

Cheers,
Peter

**Comment by chris-kent** [comment]
This has been fixed in ver 3.4
