### ISSUE TITLE
Page to blog macro is still present after page was converted to a blog post

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#22]
Hi, 

as mentioned in the topic, the page to blog macro stays on the page, even when it was convertet to a blog post. Earlier this macro was removed after a page was converted. 

Can you confirm this issue and solve it?

Grettings Max

**Comment by chris-kent** [comment]
Hi Max,

Yes this behavior is due to the new implementation Atlassian introduced in 5.10.0. I no longer do back end detection of the macro, this is all now done by the web client and as such the browser cannot remove the macro.

I don't see an issue with this as nothing is rendered on the screen by the macro (unless your license expires).

The macro can safely be deleted if someone edits the post after it is already in the blog area.

If you feel that this must be fixed, I can remove it using some new backend processing. Just say the word and I'll remove it.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,
I have done this for you, the Macro is no longer rendered in the Blog after the Template is used.
Cheers
Chris

**Comment by maximilianpeter** [comment]
Hey Chris, thanks a lot. We will try it with the next update. Greets Max
