### ISSUE TITLE
@mention emails sent before converting into Blog?

### ISSUE THREAD

**Issue by webwesen** [chris-kent/Confluence-Blog-Tools#28]
hello,

could you please shed some light if this what might happen? :

- we use 'create page via template' macro
- a correct template is used, page2blog macro is there at the very bottom
- people add @mentions in the page body
- page is saved, @mention notification emails are sent
- page2blog kicks in and converts it into a blog with today's date. (and a page gets a new URL)
- result = broken links in @mention emails already sent
 
if the above analysis is correct - could we suppress emails on an initial page save?
thank you!

Confluence : 6.2.4
Blog tools for Confluence : 3.13

**Comment by chris-kent** [comment]
Hi,

Here are my comments on the behaviour you have suggested...

- we use 'create page via template' macro - _OK, good to hear_
- a correct template is used, page2blog macro is there at the very bottom - _Excellent_
- people add @mentions in the page body -  _this is OK_
- page is saved, @mention notification emails are sent - _yes, this is correct, with broken email links, this happens independent of the Title change_
- page2blog kicks in and converts it into a blog with today's date. (and a page gets a new URL) - _This is not the normal behaviour, the plugin only renames the blog if the user creating the blog does not provide a unique blog title for this day, standard confluence Blog Title restrictions apply, if the user provides a unique Blog Title, it should not change the title_
- result = broken links in @mention emails already sent - _Unfortunately I have little control over this due to a new Atlassian architecture, I cannot intercept the Page save mechanism_

At this moment I cannot suppress the original email by the page save. I have tried to work with Atlassian, but they are not forth coming with a nice and robust solution.

I will reach out again to them to see what can be done.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,

I have submitted a trouble ticket with Atlassian, as they do not support the behavior you (and I) desire with this tool.  It is unfortunate since 5.10.0, that they changed the architecture and I no longer have control as I did in previous Confluence versions.

If you want, please vote for the issue and even add a comment as to the importance of this fix for your business.

https://jira.atlassian.com/browse/CONFSERVER-54429

Thanks
Chris

**Comment by webwesen** [comment]
voted, thanks

**Comment by chris-kent** [comment]
I have found a workaround for this, please download 3.15 and let me know if this behaves as expected.
