### ISSUE TITLE
Likes from disabled users are lost after conversion

### ISSUE THREAD

**Issue by pflan** [chris-kent/Confluence-Blog-Tools#42]
As per the subject, page Likes from disabled users are lost after conversion.

**Comment by pflan** [comment]
(I should say that because this only impacts disabled users, it's not a high priority issue.)

**Comment by pflan** [comment]
[2019-01-30-likes-for-disabled-user-not-transitioned.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/2812662/2019-01-30-likes-for-disabled-user-not-transitioned.txt)

**Comment by chris-kent** [comment]
Hi

I am looking at your issues and struggling to replicate them on my
development environment.

Disabled users attachment and liked all work.

I don't have access to AD for testing domain users, but I'm not sure if
that would make a difference.

Now looking at the log file you provided it had no information from my
plugin. Did you turn on logging as indicated?

Please try again so hopefully i can understand what is going wrong

Cheers

**Comment by pflan** [comment]
Sorry, here's a better log.
[2019-02-06-likes-for-disabled-user-not-transitioned.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/2837187/2019-02-06-likes-for-disabled-user-not-transitioned.txt)

**Comment by chris-kent** [comment]
Hi there,

After further investigation and digging into the Confluence code for how
likes are created, it is not possible for likes from disabled users to be
moved to new content. Since they have no API to move likes, I have to
create new likes, and the code under the covers prevents disabled users
from adding likes to pages.

I have now documented this as a known issue for the plugin.

There is nothing more I can do for this issue.

Chris
