### ISSUE TITLE
Edit history is lost after conversion

### ISSUE THREAD

**Issue by pflan** [chris-kent/Confluence-Blog-Tools#45]
Edit history is lost after conversion in either direction, i.e. from blog post to page and vice versa.

I guess this must be a known issue, but I couldn't find it documented anywhere. I found it surprising.

**Comment by chris-kent** [comment]
Hi there,

Yes this is the expected behaviour. Every time a page or blog is converted,
a new content entity is created which means all history is gone, and
currently the old versions of the page are lost.

This plugin has been live for 5 years and you are the first to notice (or
at least raise an issue).

I have not implemented the full history on copy, this could be possible
with some work. How important is this feature to have?

Thanks
Chris

**Comment by pflan** [comment]
It's okay, I don't think it's worth fixing.
